repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "fix-byte-order-marker"
      - id: "mixed-line-ending"
      - id: "check-merge-conflict"
      - id: "check-case-conflict"
      - id: "check-json"
      - id: "pretty-format-json"
        args:
          - "--autofix"
          - "--no-sort-keys"
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.4.58" # change to tag or sha
    hooks:
      - id: checkov_secrets
      - id: checkov
        args:
          - -d
          - "."
