{{- if empty .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3proxy.fullname" . }}-awsclient
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ include "s3proxy.clientAccessKeyId" . }}
  AWS_SECRET_ACCESS_KEY: {{ include "s3proxy.clientSecretAccessKey" . }}
{{- end }}
