{{- if and (not .Values.existingPropertiesSecret) (not .Values.csiSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3proxy.fullname" . }}
type: Opaque
data:
  s3proxy.properties: {{ (include "s3proxy.properties" .) | b64enc }}
{{- end }}
